import { bindDeposit } from '../features/deposit.js';
import { bindTransfer } from '../features/transfer.js';
import { bindWithdraw } from '../features/withdraw.js';
import { heading } from '../utils.js';

export function renderBanking(container) {
  const accountHint = '<span class="field-hint">Use the account ID, e.g. ACC-1001.</span>';
  container.innerHTML = `${heading('Money operations', 'Banking', 'Every operation requires an account number and its four-digit PIN. Review details in the confirmation step before finalising.')}<div class="operation-notice"><span>◈</span><p><strong>Safe processing</strong> — Each request is checked against the account status and available balance. Internal transfers have no service charge in this demo.</p></div><div class="two-column"><div class="section-card"><div class="section-title"><h2>Deposit money</h2><span class="operation-tag">Cash-in</span></div><form id="deposit-form"><label class="field">Account number<input name="accountNumber" autocomplete="off" required>${accountHint}</label><label class="field">PIN<input name="pin" type="password" inputmode="numeric" autocomplete="off" pattern="[0-9]{4}" maxlength="4" required></label><label class="field">Amount (BDT)<input name="amount" type="number" min="1" step="0.01" required></label><label class="field">Reference note <span class="optional">(optional)</span><input name="note" maxlength="80" placeholder="Cash counter, ATM, etc."></label><div class="form-actions"><button class="btn btn-primary">Review deposit</button></div></form></div><div class="section-card"><div class="section-title"><h2>Withdraw money</h2><span class="operation-tag">Cash-out</span></div><form id="withdraw-form"><label class="field">Account number<input name="accountNumber" autocomplete="off" required>${accountHint}</label><label class="field">PIN<input name="pin" type="password" inputmode="numeric" autocomplete="off" pattern="[0-9]{4}" maxlength="4" required></label><label class="field">Amount (BDT)<input name="amount" type="number" min="1" step="0.01" required></label><label class="field">Reference note <span class="optional">(optional)</span><input name="note" maxlength="80" placeholder="ATM or cash counter"></label><div class="form-actions"><button class="btn btn-primary">Review withdrawal</button></div></form></div></div><div class="section-card transfer-card"><div class="section-title"><div><h2>Transfer money</h2><p class="section-support">Instant internal transfer · no charge</p></div><span class="operation-tag">Internal</span></div><form id="transfer-form" class="form-grid"><label class="field">Sender account<input name="fromAccount" autocomplete="off" required>${accountHint}</label><label class="field">Sender PIN<input name="pin" type="password" inputmode="numeric" autocomplete="off" pattern="[0-9]{4}" maxlength="4" required></label><label class="field">Receiver account<input name="toAccount" autocomplete="off" required>${accountHint}</label><label class="field">Amount (BDT)<input name="amount" type="number" min="1" step="0.01" required></label><label class="field wide">Reference note <span class="optional">(optional)</span><input name="note" maxlength="80" placeholder="e.g. Rent for June"></label><div class="form-actions wide"><button class="btn btn-primary">Review transfer</button></div></form></div>`;
  bindDeposit(document.getElementById('deposit-form'));
  bindWithdraw(document.getElementById('withdraw-form'));
  bindTransfer(document.getElementById('transfer-form'));
}
