import { bindDeposit } from '../features/deposit.js';
import { bindTransfer } from '../features/transfer.js';
import { bindWithdraw } from '../features/withdraw.js';
import { heading } from '../utils.js';

export function renderBanking(container) {
  container.innerHTML = `${heading('Money operations', 'Banking', 'Every operation requires the account number and its four-digit PIN.')}<div class="two-column"><div class="section-card"><div class="section-title"><h2>Deposit money</h2></div><form id="deposit-form"><label class="field">Account number<input name="accountNumber" required></label><label class="field">PIN<input name="pin" type="password" inputmode="numeric" maxlength="4" required></label><label class="field">Amount (BDT)<input name="amount" type="number" min="1" step="0.01" required></label><label class="field">Note (optional)<input name="note" placeholder="Cash counter, ATM, etc."></label><div class="form-actions"><button class="btn btn-primary">Complete deposit</button></div></form></div><div class="section-card"><div class="section-title"><h2>Withdraw money</h2></div><form id="withdraw-form"><label class="field">Account number<input name="accountNumber" required></label><label class="field">PIN<input name="pin" type="password" inputmode="numeric" maxlength="4" required></label><label class="field">Amount (BDT)<input name="amount" type="number" min="1" step="0.01" required></label><label class="field">Note (optional)<input name="note" placeholder="ATM or cash counter"></label><div class="form-actions"><button class="btn btn-primary">Complete withdrawal</button></div></form></div></div><div class="section-card" style="margin-top:1.2rem"><div class="section-title"><h2>Transfer money</h2></div><form id="transfer-form" class="form-grid"><label class="field">Sender account<input name="fromAccount" required></label><label class="field">Sender PIN<input name="pin" type="password" inputmode="numeric" maxlength="4" required></label><label class="field">Receiver account<input name="toAccount" required></label><label class="field">Amount (BDT)<input name="amount" type="number" min="1" step="0.01" required></label><label class="field wide">Note (optional)<input name="note"></label><div class="form-actions wide"><button class="btn btn-primary">Send transfer</button></div></form></div>`;
  bindDeposit(document.getElementById('deposit-form'));
  bindWithdraw(document.getElementById('withdraw-form'));
  bindTransfer(document.getElementById('transfer-form'));
}
