import { downloadCsv } from '../features/export-csv.js';
import { getReportSummary } from '../features/reports.js';
import { empty, escapeHtml, heading, money } from '../utils.js';

export async function renderReports(container) {
  const report = await getReportSummary(); const summary = report.summary;
  container.innerHTML = `${heading('Operational insights', 'Reports', 'Monitor account status, transaction totals, and accounts that may need attention.')}<div class="stats"><div class="stat"><div class="stat-label">Active accounts</div><div class="stat-value">${summary.activeAccounts}</div></div><div class="stat"><div class="stat-label">Frozen accounts</div><div class="stat-value">${summary.frozenAccounts}</div></div><div class="stat"><div class="stat-label">All transactions</div><div class="stat-value">${summary.totalTransactions}</div></div><div class="stat"><div class="stat-label">Low balance accounts</div><div class="stat-value">${report.lowBalanceAccounts.length}</div></div></div><div class="two-column"><div class="section-card"><div class="section-title"><h2>Transaction summary</h2></div><div class="table-wrap"><table><thead><tr><th>Type</th><th>Count</th><th>Total amount</th></tr></thead><tbody>${Object.entries(summary.transactionTypes).map(([type, data]) => `<tr><td>${escapeHtml(type)}</td><td>${data.count}</td><td class="amount">${money(data.amount)}</td></tr>`).join('')}</tbody></table></div></div><div class="section-card"><div class="section-title"><h2>Low balance monitor</h2><button class="btn btn-secondary btn-small" id="export-low-balance">Export CSV</button></div><div class="table-wrap"><table><thead><tr><th>Account</th><th>Customer</th><th>Balance</th></tr></thead><tbody>${report.lowBalanceAccounts.length ? report.lowBalanceAccounts.map((account) => `<tr><td>${escapeHtml(account.accountNumber)}</td><td>${escapeHtml(account.name)}</td><td class="amount">${money(account.balance)}</td></tr>`).join('') : `<tr><td colspan="3">${empty('No accounts are below BDT 1,000.')}</td></tr>`}</tbody></table></div></div></div>`;
  document.getElementById('export-low-balance').addEventListener('click', () => downloadCsv('low-balance-accounts.csv', ['Account number', 'Customer', 'Phone', 'Balance'], report.lowBalanceAccounts.map((account) => [account.accountNumber, account.name, account.phone, account.balance])));
}
